services:
  whisperengine-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    environment:
      - ENV_MODE=discord
    env_file:
      - .env
    volumes:
      # Development code mounting (security risk - dev only)
      - ./src:/app/src:ro
      - ./prompts:/app/prompts:ro
      - ./config:/app/config:ro
      - ./run.py:/app/run.py:ro
      - ./env_manager.py:/app/env_manager.py:ro
      # Application data volumes
      - bot_backups:/app/backups
      - bot_privacy:/app/privacy_data
      - bot_temp:/app/temp_images
      - bot_logs:/app/logs
    networks:
      - whisperengine-network
    depends_on:
      - redis
      - postgres
      - qdrant
    restart: unless-stopped
    command: python run.py

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - whisperengine-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: whisper_engine
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_this_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - whisperengine-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.8.1
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - whisperengine-network
    restart: unless-stopped
    ports:
      - "6333:6333"

volumes:
  # Bot application volumes
  bot_backups:
    name: whisperengine-backups
    driver: local
  bot_privacy:
    name: whisperengine-privacy
    driver: local
  bot_temp:
    name: whisperengine-temp
    driver: local
  bot_logs:
    name: whisperengine-logs
    driver: local
  
  # Datastore volumes
  redis_data:
    name: whisperengine-redis
    driver: local
  postgres_data:
    name: whisperengine-postgres
    driver: local
  qdrant_data:
    name: whisperengine-qdrant
    driver: local

networks:
  whisperengine-network:
    driver: bridge