# Production Docker Compose Configuration
# Optimized for production deployment with external services

services:
  whisperengine-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.multi-stage
      target: production
    image: whisperengine-bot:${VERSION:-latest}
    container_name: whisperengine-bot
    restart: unless-stopped
    
    # Environment configuration
    env_file:
      - .env             # Local configuration (includes secrets like DISCORD_BOT_TOKEN)
    environment:
      # Production defaults
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG_MODE=false
      - PYTHONUNBUFFERED=1
      - HEALTH_CHECK_PORT=9090
      - HEALTH_CHECK_HOST=0.0.0.0
      - DISABLE_MEMORY_IMPORTANCE=${DISABLE_MEMORY_IMPORTANCE:-false}
      
    # Expose health check port for container orchestration
    ports:
      - "9090:9090"  # Health check endpoint
      
    # Resource limits - Optimized for multi-core processing and concurrent operations
    deploy:
      resources:
        limits:
          memory: 4G          # Increased to support 8-12 thread workers and 4-6 process workers
          cpus: '4.0'         # Increased to match application's concurrent processing needs
        reservations:
          memory: 2G          # Baseline for reliable operation
          cpus: '2.0'         # Ensure minimum cores for thread/process pools
    
    # Health check - use the built-in health endpoint
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Persistent volumes - Bot application data only
    volumes:
      # Application-specific data (NOT datastore data)
      - bot_backups:/app/backups
      - bot_privacy:/app/privacy_data
      - bot_temp:/app/temp_images
      - bot_logs:/app/logs
      # Configuration files (read-only)
      - ./prompts:/app/prompts:ro
      - ./config:/app/config:ro
      
    # Network
    networks:
      - bot_network
      
    # Dependencies with health check conditions
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: whisperengine-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - bot_network
    # Resource limits for Redis caching
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Security: Run as non-root user
    user: "999:999"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # PostgreSQL for persistent data
  postgres:
    image: postgres:16-alpine
    container_name: whisperengine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-whisper_engine}
      POSTGRES_USER: ${POSTGRES_USER:-bot_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - bot_network
    # Resource limits for PostgreSQL
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Security: Run as postgres user  
    user: "postgres:postgres"
    # Performance tuning for production
    command: >
      postgres
      -c shared_buffers=256MB
      -c max_connections=200
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bot_user} -d ${POSTGRES_DB:-whisper_engine}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  # Qdrant for vector storage (replaces ChromaDB)
  qdrant:
    image: qdrant/qdrant:v1.15.4
    container_name: whisperengine-qdrant
    restart: unless-stopped
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__LOG_LEVEL=INFO
    volumes:
      - ./data/qdrant:/qdrant/storage   # Direct bind mount for easier backup access
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    networks:
      - bot_network
    # Resource limits for Qdrant vector operations
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/6333' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Neo4j graph database
# Networks
networks:
  bot_network:
    driver: bridge
    name: whisperengine-network

# Volumes - Properly separated by service responsibility
volumes:
  # Bot application volumes (NOT datastore data)
  bot_backups:
    name: whisperengine-backups
    driver: local
  bot_privacy:
    name: whisperengine-privacy
    driver: local
  bot_temp:
    name: whisperengine-temp
    driver: local
  bot_logs:
    name: whisperengine-logs
    driver: local
  
  # Datastore volumes (managed by their respective services)
  redis_data:
    name: whisperengine-redis
    driver: local
  postgres_data:
    name: whisperengine-postgres
    driver: local
  qdrant_data:
    name: whisperengine-qdrant
    driver: local

