# Discord Bot - Development Lite Configuration
# Optimized for 12GB RAM environments
# Run from root directory: docker-compose -f docker-compose.yml -f docker-compose.dev-lite.yml up -d --build

services:
  whisperengine-bot:
    # Reduced resource limits for development environments with limited RAM
    deploy:
      resources:
        limits:
          memory: 3G          # Reduced from 4G for tighter environments
          cpus: '3.0'         # Reduced from 4.0 
        reservations:
          memory: 1.5G        # Reduced from 2G
          cpus: '1.5'         # Reduced from 2.0
    
    # Environment configuration for development
    env_file:
      - .env             # Local secrets and overrides
      
    environment:
      # Development-specific settings
      - ENV_MODE=development
      - ENVIRONMENT=development
      - DEBUG_MODE=true
      - LOG_LEVEL=DEBUG
      - FORCE_READABLE_LOGS=true
      - PYTHONUNBUFFERED=1
      # CDL Character Configuration
      - CDL_DEFAULT_CHARACTER=${CDL_DEFAULT_CHARACTER:-characters/default_assistant.json}
      
      # Reduced worker counts for development
      - MAX_WORKER_THREADS=6        # Reduced from auto-detect
      - MAX_WORKER_PROCESSES=3      # Reduced from auto-detect
      - EMOTION_MAX_WORKERS=2       # Reduced emotion workers
      - LLM_MAX_WORKERS=2          # Reduced LLM workers
      
    volumes:
      # Override the copied source code with live mounting for development
      - ./src:/app/src
      - ./characters:/app/characters
      - ./validate_config.py:/app/validate_config.py
      - ./run.py:/app/run.py
      - ./env_manager.py:/app/env_manager.py
      # System prompt templates and configuration for easy switching
      - ./config:/app/config
      # Data directory for monitoring and runtime data
      - ./data:/app/data
      # Application data volumes (persistent across restarts)
      - bot_backups:/app/backups
      - bot_privacy:/app/privacy_data
      - bot_temp:/app/temp_images
      - bot_logs:/app/logs
      
    # Expose health check port for development
    ports:
      - "9090:9090"  # Health check endpoint
      
    # Health check for development
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Enable hot-reloading by watching for changes
    command: >
      sh -c "
        echo '🔄 Development lite mode: reduced resources for 12GB environments...' &&
        python validate_config.py &&
        python -u run.py
      "
    
    # Ensure container rebuilds when source changes
    labels:
      - "dev.mode=lite"

# Development-lite specific volumes (inherit from base but add explicit definitions)
volumes:
  bot_backups:
    name: whisperengine-backups
    driver: local
  bot_privacy:
    name: whisperengine-privacy
    driver: local
  bot_temp:
    name: whisperengine-temp
    driver: local
  bot_logs:
    name: whisperengine-logs
    driver: local